version: '3.7'

services:
  # Postgres
  postgres:
    image: 'postgres:13-alpine'
    env_file:
      - './.env'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - ':::5432:5432'

  # Redis
  redis:
    image: 'redis:6-alpine'
    env_file:
      - './.env'
    volumes:
      - './data/redis:/data'
    expose:
      - '6379'

  # Prometheus
  prometheus:
    image: 'prom/prometheus:v2.25.0'
    env_file:
      - './.env'
    volumes:
      - './config/prometheus:/etc/prometheus'
      - './data/prometheus:/prometheus'
    expose:
      - '9090'

  # Grafana
  grafana:
    depends_on:
      - 'prometheus'
    #   - 'postgres'
    image: 'grafana/grafana:7.4.3'
    env_file:
      - './.env'
    volumes:
      - './data/grafana:/var/lib/grafana'
      - './config/grafana/grafana.ini:/etc/grafana/grafana.ini'
    ports:
      - '3000'

  # mpywd
  mpywd:
    image: 'kb10uy/mpywd:latest'
    env_file:
      - './.env'
    volumes:
      - './config/mpywd/config.toml:/config.toml'
    expose:
      - '4545'

  # chibisafe:
  #   depends_on:
  #     - 'postgres'
  #   build: './images/nodejs'
  #   command: 'npm run start'
  #   env_file:
  #     - './.env.chibisafe'
  #   volumes:
  #     - './data/chibisafe:/uploads'
  #   ports:
  #     - ':::5000'

  # PHP
  php:
    depends_on:
      - 'postgres'
      - 'redis'
    build: './images/php'
    volumes:
      - './config/php/php.ini:/usr/local/etc/php/php.ini'
      - './data/shaarli:/var/www/shaarli'
      - './data/kanboard:/var/www/kanboard'
      # - './data/taskboard:/var/www/taskboard'
      - './data/nextcloud:/var/www/nextcloud'
    expose:
      - '9000'

  # nginx
  nginx:
    depends_on:
      - 'prometheus'
      - 'grafana'
      - 'mpywd'
      - 'php'
    image: 'nginx:1.19-alpine'
    volumes:
      - './config/nginx/conf.d:/etc/nginx/conf.d'
      - './data/ssl:/ssl'
      - './data/shaarli:/var/www/shaarli'
      - './data/kanboard:/var/www/kanboard'
      # - './data/taskboard:/var/www/taskboard'
      - './data/nextcloud:/var/www/nextcloud'
    extra_hosts:
      - 'docker-host:172.16.0.1'
    ports:
      - '443:443'
      - '80:80'

networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '172.16.0.0/24'

