version: '3.7'

services:
  # Postgres
  postgres:
    image: 'postgres:13-alpine'
    env_file:
      - './.env'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - ':::5432:5432'

  # Redis
  redis:
    image: 'redis:6-alpine'
    env_file:
      - './.env'
    volumes:
      - './data/redis:/data'
    ports:
      - ':::6379:6379'

  # PHP
  php:
    depends_on:
      - 'postgres'
      - 'redis'
    build: './images/php'
    volumes:
      - './config/php/php.ini:/usr/local/etc/php/php.ini'
      - './data/shaarli:/var/www/shaarli'
      - './data/kanboard:/var/www/kanboard'
      - './data/taskboard:/var/www/taskboard'
      - './data/nextcloud:/var/www/nextcloud'
    ports:
      - ':::9000:9000'

  # Grafana
  grafana:
    # depends_on:
    #   - 'postgres'
    image: 'grafana/grafana:7.4.3'
    env_file:
      - './.env'
    volumes:
      - './data/grafana:/var/lib/grafana'
      - './config/grafana/grafana.ini:/etc/grafana/grafana.ini'
    ports:
      - ':::3000:3000'

  # nginx
  nginx:
    depends_on:
      - 'php'
      - 'grafana'
    image: 'nginx:1.19-alpine'
    volumes:
      - './config/nginx/conf.d:/etc/nginx/conf.d'
      - './data/ssl:/ssl'
      - './data/shaarli:/var/www/shaarli'
      - './data/kanboard:/var/www/kanboard'
      - './data/taskboard:/var/www/taskboard'
      - './data/nextcloud:/var/www/nextcloud'
    ports:
      - '443:443'
      - '80:80'

networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '172.16.0.0/24'

