version: '3.8'

services:
  # Postgres
  postgres:
    image: 'postgres:13-alpine'
    env_file:
      - './.env'
    volumes:
      - './data/postgres:/var/lib/posgresql/data'
    ports:
      - ':::5432:5432'

  # PHP
  # php:
  #   depends_on:
  #     - 'postgres'
  #   build: './images/php'
  #   ports:
  #     - ':::9000:9000'

  # # nginx
  # nginx:

networks:
  default:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '172.16.0.0/24'

